### ISSUE TITLE
ERROR: JSON-Analysis aborted

### ISSUE THREAD

**Issue by yehudimikhael** [ministryofjustice/container-check-sonar-plugin#6]
Good afternoon,

I have a problem sending the .json file to sonarqube.

```INFO: ------------- Run sensors on project
INFO: Sensor Container-Check [containercheck]
INFO: Process Container-Check report
ERROR: JSON-Analysis aborted
INFO: Process Container-Check report (done) | time=431ms
INFO: Sensor Container-Check [containercheck] (done) | time=431ms
```

sonar-scanner.properties

```sonar.projectKey=my_project
sonar.scm.disabled=true 
sonar.sources=/Users/temp/trivy/Sonarqube-node/json 
sonar.host.url=http://localhost:9000
sonar.containerCheck.jsonReportPath=./container-check-report.json
sonar.login=c52cecb021060e5f1d211a870fc0ea721b295300
```

**Comment by yehudimikhael** [comment]
```
16:43:45.901 INFO: ------------- Run sensors on project
16:43:45.909 DEBUG: 'Generic Coverage Report' skipped because one of the required properties is missing
16:43:45.909 DEBUG: 'Java CPD Block Indexer' skipped because there is no related file in current project
16:43:45.910 DEBUG: Sensors : Container-Check -> Zero Coverage Sensor
16:43:45.910 INFO: Sensor Container-Check [containercheck]
16:43:45.910 INFO: Process Container-Check report
16:43:46.224 ERROR: JSON-Analysis aborted
16:43:46.227 DEBUG: IO Problem with JSON-Report
uk.gov.justice.digital.sonar.plugin.containercheck.parser.ReportParserException: IO Problem with JSON-Report
        at uk.gov.justice.digital.sonar.plugin.containercheck.parser.JsonReportParserHelper.parse(JsonReportParserHelper.java:23)
        at uk.gov.justice.digital.sonar.plugin.containercheck.ContainerCheckSensor.parseAnalysis(ContainerCheckSensor.java:96)
        at uk.gov.justice.digital.sonar.plugin.containercheck.ContainerCheckSensor.execute(ContainerCheckSensor.java:128)
        at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
        at org.sonar.scanner.sensor.ProjectSensorsExecutor.execute(ProjectSensorsExecutor.java:49)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:356)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
        at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:144)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
        at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "Layer" (class uk.gov.justice.digital.sonar.plugin.containercheck.model.Vulnerability), not marked as ignorable (16 known properties: "FixedVersion", "References", "VulnerabilityID", "Title", "id", "Description", "Severity", "InstalledVersion", "fixedVersion", "references", "PkgName", "title", "source", "severity", "installedVersion", "description"])
 at [Source: (sun.nio.ch.ChannelInputStream); line: 73, column: 8] (through reference chain: java.util.ArrayList[0]->uk.gov.justice.digital.sonar.plugin.containercheck.model.Analysis["Vulnerabilities"]->java.util.ArrayList[0]->uk.gov.justice.digital.sonar.plugin.containercheck.model.Vulnerability["Layer"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1543)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:438)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3084)
        at uk.gov.justice.digital.sonar.plugin.containercheck.parser.JsonReportParserHelper.parse(JsonReportParserHelper.java:20)
        ... 24 common frames omitted

```

**Comment by yehudimikhael** [comment]
I checked through debugging or error below:


**Unrecognized field**

for these tags:
```
Layer
CweIDs
VendorVectors
SeveritySource
CVSS
Type
```

How do I fix this problem?
